import { workflow, node, trigger, expr } from '@n8n/workflow-sdk';

const wh_dash = trigger({ type:'n8n-nodes-base.webhook', version:2.1, config:{ name:"WH dash", parameters:{ httpMethod:"GET", path:"plat/api/dashboard", responseMode:'responseNode', options:{} } }, output:[{ headers:{}, query:{}, body:{} }] });
const g_dash_0 = node({ type:'n8n-nodes-base.dataTable', version:1.1, config:{ name:"GetI Dash", parameters:{ resource:'row', operation:'get', dataTableId:{ __rl:true, mode:'id', value:"GK9rsFAOGuolzaR8", cachedResultName:"plat_interacoes" }, matchType:'allConditions', filters:{ conditions:[{ keyName:'usuario', condition:'neq', keyValue:'__x__' }] }, returnAll:true }, executeOnce:true }, output:[{}] });
const b_dash = node({ type:'n8n-nodes-base.code', version:2, config:{ name:"Build dash", parameters:{ mode:'runOnceForAllItems', language:'javaScript', jsCode:"const req=$('WH dash').first().json;const headers=req.headers||{};const q=req.query||{};const bd=req.body||{};const a=String(headers.authorization||headers.Authorization||'');const token=(a.toLowerCase().indexOf('bearer ')===0?a.slice(7).trim():a.trim())||String(q.token||'');function tb(x){var t=String(x).replace(/-/g,'+').replace(/_/g,'/');var p=(4-(t.length%4))%4;return Buffer.from(t+'='.repeat(p),'base64');}function F(c,e){return [{json:{statusCode:c,body:{sucesso:false,erro:e}}}];}var pt=String(token).split('.');if(pt.length<2||!pt[0])return F(401,'sem_token');var U;try{U=JSON.parse(tb(pt[0]).toString('utf8'));}catch(e){return F(401,'token_invalido');}if(!U||!U.exp||new Date(U.exp).getTime()<Date.now())return F(401,'expirado');var NM={erp_estoque:'ERP · Estoque',erp_pcp:'ERP · PCP',erp_pedidos:'ERP · Pedidos',erp_fichas:'ERP · Fichas Tecnicas',erp_qualidade:'ERP · Qualidade',erp_faturamento:'ERP · Faturamento',erp_contas_pagar:'ERP · Contas a Pagar',erp_contas_receber:'ERP · Contas a Receber',erp_clientes:'ERP · Clientes'};function afs(ar){ar=String(ar||'').toLowerCase();if(ar.indexOf('diretoria')>=0)return ['erp_estoque','erp_pcp','erp_pedidos','erp_fichas','erp_qualidade','erp_faturamento','erp_contas_pagar','erp_contas_receber','erp_clientes'];if(ar.indexOf('financ')>=0)return ['erp_faturamento','erp_contas_pagar','erp_contas_receber','erp_estoque','erp_clientes'];if(ar.indexOf('industrial')>=0||ar.indexOf('pcp')>=0||ar.indexOf('qualidade')>=0)return ['erp_estoque','erp_pcp','erp_pedidos','erp_fichas','erp_qualidade','erp_clientes'];return ['erp_estoque','erp_clientes'];}var me=U.usuario;var ints=$('GetI Dash').all().map(function(i){return i.json;}).filter(function(r){return r.usuario===me;});var custo=0;ints.forEach(function(r){custo+=Number(r.custo||0);});var wk=Date.now()-7*864e5;var sem=ints.filter(function(r){return new Date(r.criado_em||r.createdAt).getTime()>=wk;}).length;var cm={};ints.forEach(function(r){var c=r.conversa_id||'';if(!c)return;var t=r.criado_em||r.createdAt;if(!cm[c])cm[c]={conversa_id:c,titulo:String(r.prompt||'Conversa').slice(0,60),n:0,atualizado_em:t};cm[c].n++;if(new Date(t)>new Date(cm[c].atualizado_em))cm[c].atualizado_em=t;});var recentes=Object.keys(cm).map(function(k){return cm[k];}).sort(function(a,b){return new Date(b.atualizado_em)-new Date(a.atualizado_em);}).slice(0,5);var fl=afs(U.area);var fontes=fl.map(function(f){return {nome:NM[f]||f,descricao:'Fonte liberada para o seu perfil',status:'conectado'};});var stats={interacoes:ints.length,interacoes_semana:sem,horas:Math.round(ints.length*4)/10,custo:custo,teto:500};return [{json:{statusCode:200,body:{stats:stats,conversas_recentes:recentes,fontes:fontes}}}];" }, executeOnce:true }, output:[{ statusCode:200, body:{} }] });
const r_dash = node({ type:'n8n-nodes-base.respondToWebhook', version:1.5, config:{ name:"Resp dash", parameters:{ respondWith:'json', responseBody: expr('{{ $json.body }}'), options:{ responseCode: expr('{{ $json.statusCode }}') } } }, output:[{}] });

const wh_hist = trigger({ type:'n8n-nodes-base.webhook', version:2.1, config:{ name:"WH hist", parameters:{ httpMethod:"GET", path:"plat/api/historico", responseMode:'responseNode', options:{} } }, output:[{ headers:{}, query:{}, body:{} }] });
const g_hist_0 = node({ type:'n8n-nodes-base.dataTable', version:1.1, config:{ name:"GetI Hist", parameters:{ resource:'row', operation:'get', dataTableId:{ __rl:true, mode:'id', value:"GK9rsFAOGuolzaR8", cachedResultName:"plat_interacoes" }, matchType:'allConditions', filters:{ conditions:[{ keyName:'usuario', condition:'neq', keyValue:'__x__' }] }, returnAll:true }, executeOnce:true }, output:[{}] });
const b_hist = node({ type:'n8n-nodes-base.code', version:2, config:{ name:"Build hist", parameters:{ mode:'runOnceForAllItems', language:'javaScript', jsCode:"const req=$('WH hist').first().json;const headers=req.headers||{};const q=req.query||{};const bd=req.body||{};const a=String(headers.authorization||headers.Authorization||'');const token=(a.toLowerCase().indexOf('bearer ')===0?a.slice(7).trim():a.trim())||String(q.token||'');function tb(x){var t=String(x).replace(/-/g,'+').replace(/_/g,'/');var p=(4-(t.length%4))%4;return Buffer.from(t+'='.repeat(p),'base64');}function F(c,e){return [{json:{statusCode:c,body:{sucesso:false,erro:e}}}];}var pt=String(token).split('.');if(pt.length<2||!pt[0])return F(401,'sem_token');var U;try{U=JSON.parse(tb(pt[0]).toString('utf8'));}catch(e){return F(401,'token_invalido');}if(!U||!U.exp||new Date(U.exp).getTime()<Date.now())return F(401,'expirado');var me=U.usuario;var ints=$('GetI Hist').all().map(function(i){return i.json;}).filter(function(r){return r.usuario===me;});var cm={};ints.forEach(function(r){var c=r.conversa_id||'';if(!c)return;var t=r.criado_em||r.createdAt;if(!cm[c])cm[c]={conversa_id:c,titulo:String(r.prompt||'Conversa').slice(0,70),n:0,ts:t,fonte:r.fonte||''};cm[c].n++;if(new Date(t)>new Date(cm[c].ts)){cm[c].ts=t;cm[c].fonte=r.fonte||cm[c].fonte;}});var arr=Object.keys(cm).map(function(k){return cm[k];}).sort(function(a,b){return new Date(b.ts)-new Date(a.ts);});function lbl(t){var d=new Date(t);var diff=(Date.now()-d.getTime())/864e5;if(diff<1)return 'Hoje';if(diff<2)return 'Ontem';if(diff<7)return 'Esta semana';if(diff<31)return 'Este mes';return 'Mais antigo';}var groups={},order=[];arr.forEach(function(c){var L=lbl(c.ts);if(!groups[L]){groups[L]=[];order.push(L);}c.hora=new Date(c.ts).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});groups[L].push(c);});var grupos=order.map(function(L){return {label:L,itens:groups[L]};});return [{json:{statusCode:200,body:{grupos:grupos}}}];" }, executeOnce:true }, output:[{ statusCode:200, body:{} }] });
const r_hist = node({ type:'n8n-nodes-base.respondToWebhook', version:1.5, config:{ name:"Resp hist", parameters:{ respondWith:'json', responseBody: expr('{{ $json.body }}'), options:{ responseCode: expr('{{ $json.statusCode }}') } } }, output:[{}] });

const wh_conv = trigger({ type:'n8n-nodes-base.webhook', version:2.1, config:{ name:"WH conv", parameters:{ httpMethod:"GET", path:"plat/api/conversa", responseMode:'responseNode', options:{} } }, output:[{ headers:{}, query:{}, body:{} }] });
const g_conv_0 = node({ type:'n8n-nodes-base.dataTable', version:1.1, config:{ name:"GetI Conv", parameters:{ resource:'row', operation:'get', dataTableId:{ __rl:true, mode:'id', value:"GK9rsFAOGuolzaR8", cachedResultName:"plat_interacoes" }, matchType:'allConditions', filters:{ conditions:[{ keyName:'usuario', condition:'neq', keyValue:'__x__' }] }, returnAll:true }, executeOnce:true }, output:[{}] });
const b_conv = node({ type:'n8n-nodes-base.code', version:2, config:{ name:"Build conv", parameters:{ mode:'runOnceForAllItems', language:'javaScript', jsCode:"const req=$('WH conv').first().json;const headers=req.headers||{};const q=req.query||{};const bd=req.body||{};const a=String(headers.authorization||headers.Authorization||'');const token=(a.toLowerCase().indexOf('bearer ')===0?a.slice(7).trim():a.trim())||String(q.token||'');function tb(x){var t=String(x).replace(/-/g,'+').replace(/_/g,'/');var p=(4-(t.length%4))%4;return Buffer.from(t+'='.repeat(p),'base64');}function F(c,e){return [{json:{statusCode:c,body:{sucesso:false,erro:e}}}];}var pt=String(token).split('.');if(pt.length<2||!pt[0])return F(401,'sem_token');var U;try{U=JSON.parse(tb(pt[0]).toString('utf8'));}catch(e){return F(401,'token_invalido');}if(!U||!U.exp||new Date(U.exp).getTime()<Date.now())return F(401,'expirado');var me=U.usuario;var id=String(q.id||'');var ints=$('GetI Conv').all().map(function(i){return i.json;}).filter(function(r){return r.usuario===me&&r.conversa_id===id;});ints.sort(function(a,b){return new Date(a.criado_em||a.createdAt)-new Date(b.criado_em||b.createdAt);});var mens=ints.map(function(r){return {prompt:r.prompt,resposta:r.resposta,fonte:r.fonte,modelo:r.modelo,custo:r.custo};});return [{json:{statusCode:200,body:{mensagens:mens}}}];" }, executeOnce:true }, output:[{ statusCode:200, body:{} }] });
const r_conv = node({ type:'n8n-nodes-base.respondToWebhook', version:1.5, config:{ name:"Resp conv", parameters:{ respondWith:'json', responseBody: expr('{{ $json.body }}'), options:{ responseCode: expr('{{ $json.statusCode }}') } } }, output:[{}] });

const wh_fontes = trigger({ type:'n8n-nodes-base.webhook', version:2.1, config:{ name:"WH fontes", parameters:{ httpMethod:"GET", path:"plat/api/fontes", responseMode:'responseNode', options:{} } }, output:[{ headers:{}, query:{}, body:{} }] });
const b_fontes = node({ type:'n8n-nodes-base.code', version:2, config:{ name:"Build fontes", parameters:{ mode:'runOnceForAllItems', language:'javaScript', jsCode:"const req=$('WH fontes').first().json;const headers=req.headers||{};const q=req.query||{};const bd=req.body||{};const a=String(headers.authorization||headers.Authorization||'');const token=(a.toLowerCase().indexOf('bearer ')===0?a.slice(7).trim():a.trim())||String(q.token||'');function tb(x){var t=String(x).replace(/-/g,'+').replace(/_/g,'/');var p=(4-(t.length%4))%4;return Buffer.from(t+'='.repeat(p),'base64');}function F(c,e){return [{json:{statusCode:c,body:{sucesso:false,erro:e}}}];}var pt=String(token).split('.');if(pt.length<2||!pt[0])return F(401,'sem_token');var U;try{U=JSON.parse(tb(pt[0]).toString('utf8'));}catch(e){return F(401,'token_invalido');}if(!U||!U.exp||new Date(U.exp).getTime()<Date.now())return F(401,'expirado');var NM={erp_estoque:'ERP · Estoque',erp_pcp:'ERP · PCP',erp_pedidos:'ERP · Pedidos',erp_fichas:'ERP · Fichas Tecnicas',erp_qualidade:'ERP · Qualidade',erp_faturamento:'ERP · Faturamento',erp_contas_pagar:'ERP · Contas a Pagar',erp_contas_receber:'ERP · Contas a Receber',erp_clientes:'ERP · Clientes'};function afs(ar){ar=String(ar||'').toLowerCase();if(ar.indexOf('diretoria')>=0)return ['erp_estoque','erp_pcp','erp_pedidos','erp_fichas','erp_qualidade','erp_faturamento','erp_contas_pagar','erp_contas_receber','erp_clientes'];if(ar.indexOf('financ')>=0)return ['erp_faturamento','erp_contas_pagar','erp_contas_receber','erp_estoque','erp_clientes'];if(ar.indexOf('industrial')>=0||ar.indexOf('pcp')>=0||ar.indexOf('qualidade')>=0)return ['erp_estoque','erp_pcp','erp_pedidos','erp_fichas','erp_qualidade','erp_clientes'];return ['erp_estoque','erp_clientes'];}var mine=afs(U.area);var minhas=mine.map(function(f){return {uid:f,nome:NM[f]||f,descricao:'Liberada para o seu perfil',tipo:'ERP',status:'conectado'};});var all=['erp_estoque','erp_pcp','erp_pedidos','erp_fichas','erp_qualidade','erp_faturamento','erp_contas_pagar','erp_contas_receber','erp_clientes'];var disp=all.filter(function(f){return mine.indexOf(f)<0;}).map(function(f){return {uid:f,nome:NM[f]||f};});return [{json:{statusCode:200,body:{minhas:minhas,disponiveis:disp}}}];" }, executeOnce:true }, output:[{ statusCode:200, body:{} }] });
const r_fontes = node({ type:'n8n-nodes-base.respondToWebhook', version:1.5, config:{ name:"Resp fontes", parameters:{ respondWith:'json', responseBody: expr('{{ $json.body }}'), options:{ responseCode: expr('{{ $json.statusCode }}') } } }, output:[{}] });

const wh_fb = trigger({ type:'n8n-nodes-base.webhook', version:2.1, config:{ name:"WH fb", parameters:{ httpMethod:"POST", path:"plat/api/feedback", responseMode:'responseNode', options:{} } }, output:[{ headers:{}, query:{}, body:{} }] });
const b_fb = node({ type:'n8n-nodes-base.code', version:2, config:{ name:"Build fb", parameters:{ mode:'runOnceForAllItems', language:'javaScript', jsCode:"const req=$('WH fb').first().json;const headers=req.headers||{};const q=req.query||{};const bd=req.body||{};const a=String(headers.authorization||headers.Authorization||'');const token=(a.toLowerCase().indexOf('bearer ')===0?a.slice(7).trim():a.trim())||String(q.token||'');function tb(x){var t=String(x).replace(/-/g,'+').replace(/_/g,'/');var p=(4-(t.length%4))%4;return Buffer.from(t+'='.repeat(p),'base64');}function F(c,e){return [{json:{statusCode:c,body:{sucesso:false,erro:e}}}];}var pt=String(token).split('.');if(pt.length<2||!pt[0])return F(401,'sem_token');var U;try{U=JSON.parse(tb(pt[0]).toString('utf8'));}catch(e){return F(401,'token_invalido');}if(!U||!U.exp||new Date(U.exp).getTime()<Date.now())return F(401,'expirado');return [{json:{statusCode:200,body:{sucesso:true}}}];" }, executeOnce:true }, output:[{ statusCode:200, body:{} }] });
const r_fb = node({ type:'n8n-nodes-base.respondToWebhook', version:1.5, config:{ name:"Resp fb", parameters:{ respondWith:'json', responseBody: expr('{{ $json.body }}'), options:{ responseCode: expr('{{ $json.statusCode }}') } } }, output:[{}] });

const wh_dest = trigger({ type:'n8n-nodes-base.webhook', version:2.1, config:{ name:"WH dest", parameters:{ httpMethod:"POST", path:"plat/api/destacar", responseMode:'responseNode', options:{} } }, output:[{ headers:{}, query:{}, body:{} }] });
const b_dest = node({ type:'n8n-nodes-base.code', version:2, config:{ name:"Build dest", parameters:{ mode:'runOnceForAllItems', language:'javaScript', jsCode:"const req=$('WH dest').first().json;const headers=req.headers||{};const q=req.query||{};const bd=req.body||{};const a=String(headers.authorization||headers.Authorization||'');const token=(a.toLowerCase().indexOf('bearer ')===0?a.slice(7).trim():a.trim())||String(q.token||'');function tb(x){var t=String(x).replace(/-/g,'+').replace(/_/g,'/');var p=(4-(t.length%4))%4;return Buffer.from(t+'='.repeat(p),'base64');}function F(c,e){return [{json:{statusCode:c,body:{sucesso:false,erro:e}}}];}var pt=String(token).split('.');if(pt.length<2||!pt[0])return F(401,'sem_token');var U;try{U=JSON.parse(tb(pt[0]).toString('utf8'));}catch(e){return F(401,'token_invalido');}if(!U||!U.exp||new Date(U.exp).getTime()<Date.now())return F(401,'expirado');return [{json:{statusCode:200,body:{sucesso:true}}}];" }, executeOnce:true }, output:[{ statusCode:200, body:{} }] });
const r_dest = node({ type:'n8n-nodes-base.respondToWebhook', version:1.5, config:{ name:"Resp dest", parameters:{ respondWith:'json', responseBody: expr('{{ $json.body }}'), options:{ responseCode: expr('{{ $json.statusCode }}') } } }, output:[{}] });

const wh_sol = trigger({ type:'n8n-nodes-base.webhook', version:2.1, config:{ name:"WH sol", parameters:{ httpMethod:"POST", path:"plat/api/solicitar", responseMode:'responseNode', options:{} } }, output:[{ headers:{}, query:{}, body:{} }] });
const b_sol = node({ type:'n8n-nodes-base.code', version:2, config:{ name:"Build sol", parameters:{ mode:'runOnceForAllItems', language:'javaScript', jsCode:"const req=$('WH sol').first().json;const headers=req.headers||{};const q=req.query||{};const bd=req.body||{};const a=String(headers.authorization||headers.Authorization||'');const token=(a.toLowerCase().indexOf('bearer ')===0?a.slice(7).trim():a.trim())||String(q.token||'');function tb(x){var t=String(x).replace(/-/g,'+').replace(/_/g,'/');var p=(4-(t.length%4))%4;return Buffer.from(t+'='.repeat(p),'base64');}function F(c,e){return [{json:{statusCode:c,body:{sucesso:false,erro:e}}}];}var pt=String(token).split('.');if(pt.length<2||!pt[0])return F(401,'sem_token');var U;try{U=JSON.parse(tb(pt[0]).toString('utf8'));}catch(e){return F(401,'token_invalido');}if(!U||!U.exp||new Date(U.exp).getTime()<Date.now())return F(401,'expirado');return [{json:{statusCode:200,body:{sucesso:true}}}];" }, executeOnce:true }, output:[{ statusCode:200, body:{} }] });
const r_sol = node({ type:'n8n-nodes-base.respondToWebhook', version:1.5, config:{ name:"Resp sol", parameters:{ respondWith:'json', responseBody: expr('{{ $json.body }}'), options:{ responseCode: expr('{{ $json.statusCode }}') } } }, output:[{}] });

export default workflow("plataforma-soul-dados", "Plataforma Soul · Dados")
  .add(wh_dash).to(g_dash_0).to(b_dash).to(r_dash)
  .add(wh_hist).to(g_hist_0).to(b_hist).to(r_hist)
  .add(wh_conv).to(g_conv_0).to(b_conv).to(r_conv)
  .add(wh_fontes).to(b_fontes).to(r_fontes)
  .add(wh_fb).to(b_fb).to(r_fb)
  .add(wh_dest).to(b_dest).to(r_dest)
  .add(wh_sol).to(b_sol).to(r_sol);
